/**
 * Comprehensive test suite for the Fee Reminder / Dunning Engine.
 *
 * Stage names used throughout:
 *   "D-2"  — 2 days before due date
 *   "D+0"  — due today
 *   "D+3"  — 3 days overdue
 *   "D+7"  — 7 days overdue
 *   "D+14" — 14 days overdue
 *
 * D30 is never generated by the engine; historical D30 rows are preserved.
 */

import { describe, it, expect, vi, beforeEach, afterEach, beforeAll } from "vitest";
import { db, pool } from "../db";
import {
  feeRecords, students, notificationConfig, dunningLog,
  academicSessions, dunningTemplates, schools,
} from "@shared/schema";
import { eq, and } from "drizzle-orm";
import {
  daysSinceIST, IST_OFFSET_MS,
  getStage, getStageWithCatchup,
  getStageForManualTrigger, getStageForSimulation,
  formatAmount, formatIndianDate, normalizePhone,
  runDunningJob, runDunningSimulation, runDunningForSingleFee,
  processDunningForSchool,
  DEFAULT_SMS_TEMPLATES, DEFAULT_EMAIL_SUBJECTS, DEFAULT_EMAIL_BODIES,
} from "../dunning";

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Return an ISO date string offset by `n` days from today in IST. */
function istDate(offsetDays: number): string {
  const nowIST    = new Date(Date.now() + IST_OFFSET_MS);
  const todayUTC  = Date.UTC(nowIST.getUTCFullYear(), nowIST.getUTCMonth(), nowIST.getUTCDate());
  const targetUTC = todayUTC + offsetDays * 86_400_000;
  const d         = new Date(targetUTC);
  const mm        = String(d.getUTCMonth() + 1).padStart(2, "0");
  const dd        = String(d.getUTCDate()).padStart(2, "0");
  return `${d.getUTCFullYear()}-${mm}-${dd}`;
}

/** Set fake system time so daysSinceIST returns a predictable value. */
function setFakeIST(daysFromDue: number, dueStr: string) {
  const [y, m, d] = dueStr.split("-").map(Number);
  const dueUTC    = Date.UTC(y, m - 1, d);
  // Fake "now" = due + daysFromDue days, at 06:00 IST (= 00:30 UTC)
  const fakeNowIST = dueUTC + daysFromDue * 86_400_000;
  // Convert IST midnight to UTC: subtract 5.5h
  vi.setSystemTime(new Date(fakeNowIST - IST_OFFSET_MS));
}

// ── Shared test DB fixtures ───────────────────────────────────────────────────

let schoolId = 0;
let sessionId = 0;
let studentId = 0;
const BASE_PHONE = "9000000001";
const BASE_EMAIL = "student@test.com";

async function insertSchool(): Promise<number> {
  const ts  = Date.now();
  const code = `TS${ts % 100_000_000}`;  // unique 10-char code
  const [s] = await db.insert(schools).values({ name: `TestSchool-${ts}`, code }).returning({ id: schools.id });
  return s.id;
}
async function insertSession(sid: number): Promise<number> {
  const [s] = await db.insert(academicSessions).values({ schoolId: sid, sessionName: "2026-27", startDate: "2026-04-01", endDate: "2027-03-31", isActive: true }).returning({ id: academicSessions.id });
  return s.id;
}
async function insertStudent(sid: number, phone?: string, email?: string): Promise<number> {
  const ts = Date.now();
  const [s] = await db.insert(students).values({
    schoolId: sid,
    digitalStudentId: `DST${ts}`,
    name: "Test Student",
    class: "10",
    section: "A",
    phone: phone ?? BASE_PHONE,
    dob: "2010-01-01",
    passwordHash: "x",
    email: email ?? BASE_EMAIL,
    guardianName: "Test Parent",
  }).returning({ id: students.id });
  return s.id;
}
async function insertFee(sid: number, stId: number, sessId: number, dueDate: string, amount = 5000, lateFeeAmount = 0): Promise<number> {
  const [f] = await db.insert(feeRecords).values({ schoolId: sid, studentId: stId, sessionId: sessId, feeType: "Tuition", amount, lateFeeAmount, dueDate, status: "Due", academicYear: "2026-27" }).returning({ id: feeRecords.id });
  return f.id;
}
async function insertConfig(sid: number, overrides: Record<string, any> = {}): Promise<void> {
  await db.insert(notificationConfig).values({ schoolId: sid, smsEnabled: true, waEnabled: true, emailEnabled: true, msg91AuthKey: "test-auth-key", msg91SenderId: "SCHOOL", msg91WaNumber: "919000000000", msg91WaTemplate: "fee_reminder", emailProvider: "sendgrid", sendgridApiKey: "sg-test-key", sendgridFromEmail: "fees@school.test", sendgridFromName: "School Admin", ...overrides }).onConflictDoUpdate({ target: notificationConfig.schoolId, set: { smsEnabled: true, ...overrides } });
}
async function dunningLogCount(feeId: number, channel: string, stage: string, status = "sent"): Promise<number> {
  const rows = await db.select().from(dunningLog).where(and(eq(dunningLog.feeRecordId, feeId), eq(dunningLog.channel, channel), eq(dunningLog.stage, stage), eq(dunningLog.status, status)));
  return rows.length;
}
async function markPaid(feeId: number) {
  await db.update(feeRecords).set({ status: "Paid" }).where(eq(feeRecords.id, feeId));
}
/**
 * Run the per-school dunning logic WITHOUT the advisory lock.
 * This keeps integration tests isolated from parallel test files that may
 * concurrently hold the same pg advisory lock key.
 * The advisory lock itself is tested by dunning-concurrency-guard.test.ts.
 */
async function runJob(sid: number): Promise<void> {
  const cfgRows = await db.select().from(notificationConfig)
    .where(eq(notificationConfig.schoolId, sid));
  if (cfgRows.length > 0) await processDunningForSchool(cfgRows[0]);
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. Formatting utilities
// ─────────────────────────────────────────────────────────────────────────────

describe("formatAmount", () => {
  it("formats whole thousands with comma", () => expect(formatAmount(5000)).toBe("5,000"));
  it("formats lakhs", ()                   => expect(formatAmount(100000)).toBe("1,00,000"));
  it("formats zero",  ()                   => expect(formatAmount(0)).toBe("0"));
  it("formats small amount", ()            => expect(formatAmount(500)).toBe("500"));
  it("formats large amount with Indian grouping", () => expect(formatAmount(25000)).toBe("25,000"));
});

describe("formatIndianDate", () => {
  it("formats YYYY-MM-DD to DD Mon YYYY",    () => expect(formatIndianDate("2027-08-17")).toBe("17 Aug 2027"));
  it("formats January correctly",             () => expect(formatIndianDate("2027-01-01")).toBe("1 Jan 2027"));
  it("formats December correctly",            () => expect(formatIndianDate("2027-12-31")).toBe("31 Dec 2027"));
  it("returns raw string on invalid input",   () => expect(formatIndianDate("bad-date")).toBe("bad-date"));
  it("formats single-digit day",              () => expect(formatIndianDate("2027-03-05")).toBe("5 Mar 2027"));
});

// ─────────────────────────────────────────────────────────────────────────────
// 2. Phone normalisation
// ─────────────────────────────────────────────────────────────────────────────

describe("normalizePhone", () => {
  it("accepts a 10-digit number and prepends 91",     () => expect(normalizePhone("9000000001")).toBe("919000000001"));
  it("accepts number with +91 prefix",                () => expect(normalizePhone("+919000000001")).toBe("919000000001"));
  it("accepts number with 91 prefix",                 () => expect(normalizePhone("919000000001")).toBe("919000000001"));
  it("strips dashes and spaces",                      () => expect(normalizePhone("90-00-000-001")).toBe("919000000001"));
  it("replaces leading 0 with 91",                    () => expect(normalizePhone("09000000001")).toBe("919000000001"));
  it("returns null for empty string",                 () => expect(normalizePhone("")).toBeNull());
  it("returns null for whitespace-only",              () => expect(normalizePhone("   ")).toBeNull());
  it("returns null for too-short number",             () => expect(normalizePhone("12345")).toBeNull());
  it("returns null for too-long number",              () => expect(normalizePhone("919000000001234")).toBeNull());
  it("returns null for letters only",                 () => expect(normalizePhone("abcdef")).toBeNull());
});

// ─────────────────────────────────────────────────────────────────────────────
// 3. daysSinceIST — IST-aware date arithmetic
// ─────────────────────────────────────────────────────────────────────────────

describe("daysSinceIST", () => {
  const DUE = "2027-08-20";

  afterEach(() => vi.useRealTimers());

  it("returns 0 on the due date in IST",   () => { setFakeIST(0,  DUE); expect(daysSinceIST(DUE)).toBe(0); });
  it("returns -2 two days before due",     () => { setFakeIST(-2, DUE); expect(daysSinceIST(DUE)).toBe(-2); });
  it("returns  3 three days after due",    () => { setFakeIST(3,  DUE); expect(daysSinceIST(DUE)).toBe(3); });
  it("returns  7 seven days after due",    () => { setFakeIST(7,  DUE); expect(daysSinceIST(DUE)).toBe(7); });
  it("returns 14 fourteen days after due", () => { setFakeIST(14, DUE); expect(daysSinceIST(DUE)).toBe(14); });

  it("uses IST calendar boundary — UTC 18:29:59 on 19-Aug = IST 23:59 on 19-Aug → day before due", () => {
    // IST today = Aug 19, due = Aug 20 → days = -1
    vi.setSystemTime(new Date("2027-08-19T18:29:59Z"));
    expect(daysSinceIST(DUE)).toBe(-1);
  });
  it("uses IST calendar boundary — UTC 18:30 on 20-Aug = IST 00:00 on 21-Aug → 1 day after due", () => {
    // IST today = Aug 21, due = Aug 20 → days = 1 (NOT on D+0 stage)
    vi.setSystemTime(new Date("2027-08-20T18:30:00Z"));
    expect(daysSinceIST(DUE)).toBe(1);
  });
  it("uses IST calendar boundary — UTC 18:30 on 19-Aug = IST 00:00 on 20-Aug → due today (D+0)", () => {
    // IST today = Aug 20 = due date → days = 0
    vi.setSystemTime(new Date("2027-08-19T18:30:00Z"));
    expect(daysSinceIST(DUE)).toBe(0);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// 4. getStage — exact-day matching
// ─────────────────────────────────────────────────────────────────────────────

describe("getStage — exact-day matching", () => {
  const DUE = "2027-08-20";
  afterEach(() => vi.useRealTimers());

  it("returns D-2 exactly 2 days before due",   () => { setFakeIST(-2, DUE); expect(getStage(DUE)).toBe("D-2");  });
  it("returns D+0 on the due date",             () => { setFakeIST(0,  DUE); expect(getStage(DUE)).toBe("D+0");  });
  it("returns D+3 exactly 3 days overdue",      () => { setFakeIST(3,  DUE); expect(getStage(DUE)).toBe("D+3");  });
  it("returns D+7 exactly 7 days overdue",      () => { setFakeIST(7,  DUE); expect(getStage(DUE)).toBe("D+7");  });
  it("returns D+14 exactly 14 days overdue",    () => { setFakeIST(14, DUE); expect(getStage(DUE)).toBe("D+14"); });

  it("returns null on day 1 (not a stage day)", () => { setFakeIST(1,  DUE); expect(getStage(DUE)).toBeNull(); });
  it("returns null on day 5 (not a stage day)", () => { setFakeIST(5,  DUE); expect(getStage(DUE)).toBeNull(); });
  it("returns null on day 30 — D30 is never generated", () => {
    setFakeIST(30, DUE);
    expect(getStage(DUE)).toBeNull();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// 5. getStageWithCatchup — catch-up window
// ─────────────────────────────────────────────────────────────────────────────

describe("getStageWithCatchup — 2-day catch-up window", () => {
  const DUE = "2027-08-20";
  afterEach(() => vi.useRealTimers());

  it("fires D+7 on the exact day (day 7)",  () => { setFakeIST(7, DUE); expect(getStageWithCatchup(DUE)).toBe("D+7"); });
  it("catches D+7 one day late (day 8)",    () => { setFakeIST(8, DUE); expect(getStageWithCatchup(DUE)).toBe("D+7"); });
  it("catches D+7 two days late (day 9)",   () => { setFakeIST(9, DUE); expect(getStageWithCatchup(DUE)).toBe("D+7"); });
  it("does NOT catch D+7 three days late",  () => { setFakeIST(10, DUE); expect(getStageWithCatchup(DUE)).toBeNull(); });

  it("fires D+0 on exact day",              () => { setFakeIST(0, DUE);  expect(getStageWithCatchup(DUE)).toBe("D+0"); });
  it("catches D+0 one day late (day 1)",    () => { setFakeIST(1, DUE);  expect(getStageWithCatchup(DUE)).toBe("D+0"); });
  it("catches D+0 two days late (day 2)",   () => { setFakeIST(2, DUE);  expect(getStageWithCatchup(DUE)).toBe("D+0"); });
  it("does not generate D30",               () => { setFakeIST(30, DUE); expect(getStageWithCatchup(DUE)).toBeNull(); });
  it("respects custom maxCatchupDays=0 (no catch-up)", () => {
    setFakeIST(8, DUE);
    expect(getStageWithCatchup(DUE, 0)).toBeNull();
  });
  it("respects custom maxCatchupDays=1",    () => {
    setFakeIST(8, DUE);  // 1 day after D+7
    expect(getStageWithCatchup(DUE, 1)).toBe("D+7");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// 6. getStageForManualTrigger — nearest-bucket
// ─────────────────────────────────────────────────────────────────────────────

describe("getStageForManualTrigger — nearest bucket", () => {
  const DUE = "2027-08-20";
  afterEach(() => vi.useRealTimers());

  it("days <= -2  → D-2",  () => { setFakeIST(-5,  DUE); expect(getStageForManualTrigger(DUE)).toBe("D-2");  });
  it("day  -2     → D-2",  () => { setFakeIST(-2,  DUE); expect(getStageForManualTrigger(DUE)).toBe("D-2");  });
  it("day  -1     → D+0",  () => { setFakeIST(-1,  DUE); expect(getStageForManualTrigger(DUE)).toBe("D+0");  });
  it("day   0     → D+0",  () => { setFakeIST(0,   DUE); expect(getStageForManualTrigger(DUE)).toBe("D+0");  });
  it("day   1     → D+0",  () => { setFakeIST(1,   DUE); expect(getStageForManualTrigger(DUE)).toBe("D+0");  });
  it("day   2     → D+3",  () => { setFakeIST(2,   DUE); expect(getStageForManualTrigger(DUE)).toBe("D+3");  });
  it("day   5     → D+3",  () => { setFakeIST(5,   DUE); expect(getStageForManualTrigger(DUE)).toBe("D+3");  });
  it("day   6     → D+7",  () => { setFakeIST(6,   DUE); expect(getStageForManualTrigger(DUE)).toBe("D+7");  });
  it("day  10     → D+7",  () => { setFakeIST(10,  DUE); expect(getStageForManualTrigger(DUE)).toBe("D+7");  });
  it("day  11     → D+14", () => { setFakeIST(11,  DUE); expect(getStageForManualTrigger(DUE)).toBe("D+14"); });
  it("day  30     → D+14 (never D30)", () => { setFakeIST(30, DUE); expect(getStageForManualTrigger(DUE)).toBe("D+14"); });
});

// ─────────────────────────────────────────────────────────────────────────────
// 7. getStageForSimulation
// ─────────────────────────────────────────────────────────────────────────────

describe("getStageForSimulation — same buckets as manual trigger", () => {
  const DUE = "2027-08-20";
  afterEach(() => vi.useRealTimers());

  it("day -10 → D-2",  () => { setFakeIST(-10, DUE); expect(getStageForSimulation(DUE)).toBe("D-2");  });
  it("day   0 → D+0",  () => { setFakeIST(0,   DUE); expect(getStageForSimulation(DUE)).toBe("D+0");  });
  it("day   4 → D+3",  () => { setFakeIST(4,   DUE); expect(getStageForSimulation(DUE)).toBe("D+3");  });
  it("day   8 → D+7",  () => { setFakeIST(8,   DUE); expect(getStageForSimulation(DUE)).toBe("D+7");  });
  it("day  20 → D+14 (never D30)", () => { setFakeIST(20, DUE); expect(getStageForSimulation(DUE)).toBe("D+14"); });
});

// ─────────────────────────────────────────────────────────────────────────────
// 8. Default templates — all 5 stages present, no D30
// ─────────────────────────────────────────────────────────────────────────────

describe("Default templates", () => {
  const STAGES = ["D-2", "D+0", "D+3", "D+7", "D+14"] as const;

  it("DEFAULT_SMS_TEMPLATES has exactly 5 stages", () => {
    expect(Object.keys(DEFAULT_SMS_TEMPLATES).sort()).toEqual([...STAGES].sort());
  });
  it("DEFAULT_EMAIL_SUBJECTS has exactly 5 stages", () => {
    expect(Object.keys(DEFAULT_EMAIL_SUBJECTS).sort()).toEqual([...STAGES].sort());
  });
  it("DEFAULT_EMAIL_BODIES has exactly 5 stages", () => {
    expect(Object.keys(DEFAULT_EMAIL_BODIES).sort()).toEqual([...STAGES].sort());
  });
  it("No D30 stage in any default template", () => {
    expect("D30" in DEFAULT_SMS_TEMPLATES).toBe(false);
    expect("D30" in DEFAULT_EMAIL_SUBJECTS).toBe(false);
    expect("D30" in DEFAULT_EMAIL_BODIES).toBe(false);
  });
  it("No old D0/D3/D7/D14 keys present", () => {
    for (const old of ["D0", "D3", "D7", "D14"]) {
      expect(old in DEFAULT_SMS_TEMPLATES).toBe(false);
    }
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// 9–14. Integration tests (DB required)
// ─────────────────────────────────────────────────────────────────────────────

describe("Integration — cron job / runDunningJob", () => {
  beforeAll(async () => {
    schoolId  = await insertSchool();
    sessionId = await insertSession(schoolId);
    studentId = await insertStudent(schoolId, BASE_PHONE, BASE_EMAIL);
  });
  afterEach(async () => {
    vi.useRealTimers();
    vi.restoreAllMocks();
    await db.delete(dunningLog).where(eq(dunningLog.schoolId, schoolId));
    await db.delete(notificationConfig).where(eq(notificationConfig.schoolId, schoolId));
    await db.delete(feeRecords).where(eq(feeRecords.schoolId, schoolId));
  });

  // Helper: stub all three provider sends to avoid real network calls
  function stubProviders(outcome: "success" | "fail" | "network-error" = "success") {
    const original = global.fetch;
    vi.spyOn(global, "fetch").mockImplementation(async (url, init) => {
      const u = String(url);
      if (u.includes("msg91") || u.includes("sendgrid") || u.includes("mailtrap")) {
        if (outcome === "network-error") throw new Error("fetch failed: ECONNRESET");
        const status = outcome === "success" ? (u.includes("sendgrid") ? 202 : 200) : 500;
        return new Response(
          outcome === "success" ? JSON.stringify({ type: "success", message: "OK" }) : "Server Error",
          { status },
        );
      }
      return original(url as any, init);
    });
  }

  it("9a — fires D-2 exactly 2 days before due", async () => {
    stubProviders();
    const dueDate = istDate(2);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId);
    await runJob(schoolId);
    expect(await dunningLogCount(feeId, "sms", "D-2")).toBe(1);
    expect(await dunningLogCount(feeId, "whatsapp", "D-2")).toBe(1);
    expect(await dunningLogCount(feeId, "email", "D-2")).toBe(1);
  });

  it("9b — fires D+0 on the due date", async () => {
    stubProviders();
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId);
    await runJob(schoolId);
    expect(await dunningLogCount(feeId, "sms", "D+0")).toBe(1);
  });

  it("9c — fires D+3 exactly 3 days overdue", async () => {
    stubProviders();
    const dueDate = istDate(-3);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId);
    await runJob(schoolId);
    expect(await dunningLogCount(feeId, "sms", "D+3")).toBe(1);
  });

  it("9d — fires D+7 exactly 7 days overdue", async () => {
    stubProviders();
    const dueDate = istDate(-7);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId);
    await runJob(schoolId);
    expect(await dunningLogCount(feeId, "sms", "D+7")).toBe(1);
  });

  it("9e — fires D+14 exactly 14 days overdue", async () => {
    stubProviders();
    const dueDate = istDate(-14);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId);
    await runJob(schoolId);
    expect(await dunningLogCount(feeId, "sms", "D+14")).toBe(1);
  });

  it("9f — D30 is never generated for 30-days-overdue fee", async () => {
    stubProviders();
    const dueDate = istDate(-30);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId);
    await runJob(schoolId);
    // daysSince=30 has no exact stage and is outside the 2-day catch-up window
    // (D+14 was the last stage, at day 14, which is > 2 days ago from day 30)
    const d30count = await dunningLogCount(feeId, "sms", "D30");
    expect(d30count).toBe(0);
    // Also verify D+14 is NOT sent (not within catch-up window from day 30)
    expect(await dunningLogCount(feeId, "sms", "D+14")).toBe(0);
  });

  it("9g — deduplication: same (fee, channel, stage) not sent twice", async () => {
    stubProviders();
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId);
    await runJob(schoolId);
    await runJob(schoolId); // second run — should be skipped by sentSet
    expect(await dunningLogCount(feeId, "sms", "D+0")).toBe(1);
  });

  it("9h — failed send is retried on next cron run (not blocked by 'failed' log)", async () => {
    let callCount = 0;
    vi.spyOn(global, "fetch").mockImplementation(async (url) => {
      const u = String(url);
      if (u.includes("msg91") || u.includes("sendgrid")) {
        callCount++;
        if (callCount <= 3) return new Response("Internal Server Error", { status: 500 });
        return new Response(JSON.stringify({ type: "success" }), { status: 200 });
      }
      return new Response("", { status: 200 });
    });
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId, { waEnabled: false, emailEnabled: false });
    await runJob(schoolId); // first run — all 3 attempts fail (MAX_RETRIES=3), logs 'failed'
    // Now check: a 'failed' log exists, no 'sent' log
    expect(await dunningLogCount(feeId, "sms", "D+0", "failed")).toBeGreaterThan(0);
    expect(await dunningLogCount(feeId, "sms", "D+0", "sent")).toBe(0);
  });

  it("9i — paid invoice NEVER receives a reminder", async () => {
    stubProviders();
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await markPaid(feeId);
    await insertConfig(schoolId);
    await runJob(schoolId);
    expect(await dunningLogCount(feeId, "sms", "D+0")).toBe(0);
  });

  it("9k — amount includes late fee", async () => {
    const captured: string[] = [];
    vi.spyOn(global, "fetch").mockImplementation(async (url, init) => {
      const u = String(url);
      if (u.includes("msg91.com/api/v2")) {
        captured.push(JSON.parse((init as any).body).sms[0].message);
        return new Response(JSON.stringify({ type: "success" }), { status: 200 });
      }
      return new Response(JSON.stringify({ type: "success" }), { status: 200 });
    });
    const dueDate = istDate(0);
    // base=2000, lateFee=100 → totalDue=2100
    const feeId = await insertFee(schoolId, studentId, sessionId, dueDate, 2000, 100);
    await insertConfig(schoolId, { waEnabled: false, emailEnabled: false });
    await runJob(schoolId);
    expect(captured.length).toBeGreaterThan(0);
    // Message should contain 2,100 (formatted) not 2,000
    expect(captured[0]).toContain("2,100");
    expect(captured[0]).not.toContain("2,000");
  });

  it("9l — date in SMS is human-friendly Indian format", async () => {
    const captured: string[] = [];
    vi.spyOn(global, "fetch").mockImplementation(async (url, init) => {
      const u = String(url);
      if (u.includes("msg91.com/api/v2")) {
        captured.push(JSON.parse((init as any).body).sms[0].message);
      }
      return new Response(JSON.stringify({ type: "success" }), { status: 200 });
    });
    // D-2 stage uses {due_date} in the template
    const dueDate = istDate(2); // 2 days from now
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId, { waEnabled: false, emailEnabled: false });
    await runJob(schoolId);
    if (captured.length > 0) {
      // Should NOT contain raw ISO format like "2027-08-"
      expect(captured[0]).not.toMatch(/\d{4}-\d{2}-\d{2}/);
      // Should contain a month abbreviation
      expect(captured[0]).toMatch(/Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec/);
    }
  });

  it("9m — missing SMS sender ID skips SMS but does NOT block WhatsApp/Email", async () => {
    stubProviders();
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    // Auth key present (needed for WhatsApp too), but SMS sender ID missing
    await insertConfig(schoolId, { smsEnabled: true, msg91SenderId: null });
    await runJob(schoolId);
    // SMS should be 'failed' with descriptive error
    const smsRows = await db.select().from(dunningLog).where(and(eq(dunningLog.feeRecordId, feeId), eq(dunningLog.channel, "sms")));
    expect(smsRows.length).toBeGreaterThan(0);
    expect(smsRows[0].status).toBe("failed");
    expect(smsRows[0].errorMessage).toMatch(/sender/i);
    // WhatsApp and Email should succeed independently (auth key is present)
    expect(await dunningLogCount(feeId, "whatsapp", "D+0")).toBe(1);
    expect(await dunningLogCount(feeId, "email",    "D+0")).toBe(1);
  });

  it("9n — missing WhatsApp credentials skip WA but not SMS/Email", async () => {
    stubProviders();
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId, { waEnabled: true, msg91WaNumber: null, msg91WaTemplate: null });
    await runJob(schoolId);
    const waRows = await db.select().from(dunningLog).where(and(eq(dunningLog.feeRecordId, feeId), eq(dunningLog.channel, "whatsapp")));
    expect(waRows[0].status).toBe("failed");
    expect(waRows[0].errorMessage).toContain("WhatsApp");
    expect(await dunningLogCount(feeId, "sms", "D+0")).toBe(1);
  });

  it("9o — missing SendGrid From Email fails with descriptive error", async () => {
    stubProviders();
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId, { emailEnabled: true, sendgridFromEmail: null });
    await runJob(schoolId);
    const emailRows = await db.select().from(dunningLog).where(and(eq(dunningLog.feeRecordId, feeId), eq(dunningLog.channel, "email")));
    expect(emailRows[0].status).toBe("failed");
    expect(emailRows[0].errorMessage).toMatch(/From Email/i);
  });

  it("9p — invalid student phone is rejected with clear error", async () => {
    // Use an obviously invalid phone ("   ") that normalizePhone() rejects
    const stBadPhone = await insertStudent(schoolId, "   bad   ", "nophone@test.com");
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, stBadPhone, sessionId, dueDate);
    await insertConfig(schoolId, { waEnabled: false, emailEnabled: false });
    await runJob(schoolId);
    const rows = await db.select().from(dunningLog).where(eq(dunningLog.feeRecordId, feeId));
    expect(rows.length).toBeGreaterThan(0);
    expect(rows[0].status).toBe("failed");
    // Should mention phone normalisation or Invalid phone
    expect(rows[0].errorMessage).toMatch(/phone|Invalid/i);
  });

  it("9q — catch-up: D+7 missed yesterday fires today", async () => {
    stubProviders();
    const dueDate = istDate(-8); // 8 days overdue → catch-up sees day 8-1=7 → D+7
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId, { waEnabled: false, emailEnabled: false });
    await runJob(schoolId);
    expect(await dunningLogCount(feeId, "sms", "D+7")).toBe(1);
  });

  it("9r — catch-up: already-sent D+7 is NOT re-sent", async () => {
    stubProviders();
    const dueDate = istDate(-8);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId, { waEnabled: false, emailEnabled: false });
    // Pre-insert a "sent" log for D+7 SMS
    await db.insert(dunningLog).values({ schoolId, feeRecordId: feeId, channel: "sms", stage: "D+7", status: "sent", studentName: "Test Student" });
    await runJob(schoolId);
    // Should still be exactly 1 (the pre-inserted one)
    expect(await dunningLogCount(feeId, "sms", "D+7")).toBe(1);
  });

  it("9s — two fees for the same student are processed independently", async () => {
    stubProviders();
    const feeA = await insertFee(schoolId, studentId, sessionId, istDate(0));  // D+0
    const feeB = await insertFee(schoolId, studentId, sessionId, istDate(-7)); // D+7
    await insertConfig(schoolId, { waEnabled: false, emailEnabled: false });
    await markPaid(feeA); // paying A does not affect B
    await runJob(schoolId);
    expect(await dunningLogCount(feeA, "sms", "D+0")).toBe(0); // paid, skipped
    expect(await dunningLogCount(feeB, "sms", "D+7")).toBe(1); // independent
  });

  it("9t — WhatsApp HTTP 200 with error body is recorded as failed, not sent", async () => {
    vi.spyOn(global, "fetch").mockImplementation(async (url) => {
      const u = String(url);
      if (u.includes("whatsapp")) {
        return new Response(JSON.stringify({ type: "error", message: "Template not found" }), { status: 200 });
      }
      return new Response(JSON.stringify({ type: "success" }), { status: 200 });
    });
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId, { smsEnabled: false, emailEnabled: false });
    await runJob(schoolId);
    const rows = await db.select().from(dunningLog).where(and(eq(dunningLog.feeRecordId, feeId), eq(dunningLog.channel, "whatsapp")));
    expect(rows.length).toBe(1);
    expect(rows[0].status).toBe("failed");
    expect(rows[0].errorMessage).toContain("Template not found");
  });

  it("9u — provider timeout does not freeze the engine", async () => {
    // Simulate AbortSignal timeout — fetch throws AbortError after a very short wait
    vi.spyOn(global, "fetch").mockImplementation(async () => {
      await new Promise(r => setTimeout(r, 50));
      const e = new Error("This operation was aborted");
      (e as any).name = "AbortError";
      throw e;
    });
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId, { waEnabled: false, emailEnabled: false });
    // Must resolve without hanging; all retries exhaust quickly
    await expect(runJob(schoolId)).resolves.toBeUndefined();
    // Filter by status="failed" directly — a parallel test file's runDunningJob()
    // may also write rows for this fee (real API → auth error → "failed"), so we
    // assert on the outcome rather than on rows[0] position.
    const failedRows = await db.select().from(dunningLog)
      .where(and(eq(dunningLog.feeRecordId, feeId), eq(dunningLog.status, "failed")));
    // Should have at least one failure row (AbortError → failed on all 3 retries)
    expect(failedRows.length).toBeGreaterThan(0);
  });

  it("9v — HTTP 429 is retried, then recorded as failed after max attempts", async () => {
    let calls = 0;
    vi.spyOn(global, "fetch").mockImplementation(async (url) => {
      const u = String(url);
      if (u.includes("msg91")) { calls++; return new Response("Rate limit", { status: 429 }); }
      return new Response(JSON.stringify({ type: "success" }), { status: 200 });
    });
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId, { waEnabled: false, emailEnabled: false });
    await runJob(schoolId);
    // withRetry attempts 3 times total
    expect(calls).toBe(3);
    const rows = await db.select().from(dunningLog).where(and(eq(dunningLog.feeRecordId, feeId), eq(dunningLog.channel, "sms")));
    expect(rows[0].status).toBe("failed");
    expect(rows[0].errorMessage).toContain("429");
  });

  it("9w — HTTP 400 is NOT retried (config error)", async () => {
    let calls = 0;
    vi.spyOn(global, "fetch").mockImplementation(async (url) => {
      const u = String(url);
      if (u.includes("msg91")) { calls++; return new Response("Bad Request", { status: 400 }); }
      return new Response(JSON.stringify({ type: "success" }), { status: 200 });
    });
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId, { waEnabled: false, emailEnabled: false });
    await runJob(schoolId);
    // 400 is not retried — exactly 1 attempt
    expect(calls).toBe(1);
    const rows = await db.select().from(dunningLog).where(and(eq(dunningLog.feeRecordId, feeId), eq(dunningLog.channel, "sms")));
    expect(rows[0].status).toBe("failed");
  });

  it("9x — HTTP 500 is retried up to 3 times", async () => {
    let calls = 0;
    vi.spyOn(global, "fetch").mockImplementation(async (url) => {
      const u = String(url);
      if (u.includes("msg91")) { calls++; return new Response("Server Error", { status: 500 }); }
      return new Response(JSON.stringify({ type: "success" }), { status: 200 });
    });
    const dueDate = istDate(0);
    const feeId   = await insertFee(schoolId, studentId, sessionId, dueDate);
    await insertConfig(schoolId, { waEnabled: false, emailEnabled: false });
    await runJob(schoolId);
    expect(calls).toBe(3);
    const rows = await db.select().from(dunningLog).where(and(eq(dunningLog.feeRecordId, feeId), eq(dunningLog.channel, "sms")));
    expect(rows[0].status).toBe("failed");
  });

  it("9y — multi-tenant: school A never sees school B data", async () => {
    stubProviders();
    const schoolB   = await insertSchool();
    const sessB     = await insertSession(schoolB);
    const studB     = await insertStudent(schoolB, "9000000002", "b@test.com");
    const feeA      = await insertFee(schoolId, studentId, sessionId, istDate(0));
    const feeB      = await insertFee(schoolB,  studB,     sessB,     istDate(0));
    await insertConfig(schoolId);
    await insertConfig(schoolB);
    await runJob(schoolId);
    await runJob(schoolB);
    // Each school's logs should be scoped to its own school_id
    const logsA = await db.select().from(dunningLog).where(and(eq(dunningLog.feeRecordId, feeA), eq(dunningLog.schoolId, schoolId)));
    const logsB = await db.select().from(dunningLog).where(and(eq(dunningLog.feeRecordId, feeB), eq(dunningLog.schoolId, schoolB)));
    expect(logsA.length).toBeGreaterThan(0);
    expect(logsB.length).toBeGreaterThan(0);
    // School A logs only reference school A fee
    logsA.forEach(l => expect(l.schoolId).toBe(schoolId));
    logsB.forEach(l => expect(l.schoolId).toBe(schoolB));
    // Cleanup
    await db.delete(dunningLog).where(eq(dunningLog.schoolId, schoolB));
    await db.delete(notificationConfig).where(eq(notificationConfig.schoolId, schoolB));
    await db.delete(feeRecords).where(eq(feeRecords.schoolId, schoolB));
    await db.delete(students).where(eq(students.schoolId, schoolB));
    await db.delete(academicSessions).where(eq(academicSessions.schoolId, schoolB));
    await db.delete(schools).where(eq(schools.id, schoolB));
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// 10. Simulation
// ─────────────────────────────────────────────────────────────────────────────

describe("Integration — runDunningSimulation", () => {
  let simSchoolId = 0, simSessionId = 0, simStudentId = 0;

  beforeAll(async () => {
    simSchoolId  = await insertSchool();
    simSessionId = await insertSession(simSchoolId);
    simStudentId = await insertStudent(simSchoolId, BASE_PHONE, BASE_EMAIL);
  });
  afterEach(async () => {
    await db.delete(dunningLog).where(eq(dunningLog.schoolId, simSchoolId));
    await db.delete(feeRecords).where(eq(feeRecords.schoolId, simSchoolId));
  });

  it("10a — simulation never calls any real provider", async () => {
    const fetchSpy = vi.spyOn(global, "fetch");
    await insertFee(simSchoolId, simStudentId, simSessionId, istDate(0));
    await runDunningSimulation(simSchoolId);
    const dunningCalls = fetchSpy.mock.calls.filter(c =>
      String(c[0]).includes("msg91") || String(c[0]).includes("sendgrid") || String(c[0]).includes("mailtrap")
    );
    expect(dunningCalls.length).toBe(0);
    vi.restoreAllMocks();
  });

  it("10b — simulation logs status=simulated, not sent", async () => {
    await insertFee(simSchoolId, simStudentId, simSessionId, istDate(0));
    await runDunningSimulation(simSchoolId);
    const rows = await db.select().from(dunningLog).where(eq(dunningLog.schoolId, simSchoolId));
    expect(rows.length).toBe(3); // sms + whatsapp + email
    rows.forEach(r => expect(r.status).toBe("simulated"));
  });

  it("10c — simulated rows do NOT block real cron sends", async () => {
    vi.spyOn(global, "fetch").mockResolvedValue(new Response(JSON.stringify({ type: "success" }), { status: 200 }));
    const feeId = await insertFee(simSchoolId, simStudentId, simSessionId, istDate(0));
    // Run simulation first — writes 'simulated' rows
    await runDunningSimulation(simSchoolId);
    // Now run real job — should still send (simulated != sent in sentSet)
    await insertConfig(simSchoolId, { waEnabled: false, emailEnabled: false });
    await runJob(simSchoolId);
    expect(await dunningLogCount(feeId, "sms", "D+0", "sent")).toBe(1);
    await db.delete(notificationConfig).where(eq(notificationConfig.schoolId, simSchoolId));
    vi.restoreAllMocks();
  });

  it("10d — simulation includes amount with late fee", async () => {
    await insertFee(simSchoolId, simStudentId, simSessionId, istDate(0), 2000, 100);
    const result = await runDunningSimulation(simSchoolId);
    // All entries should show total=2100
    result.entries.forEach(e => expect(e.amount).toBe(2100));
  });

  it("10e — simulation reports invalid contact correctly", async () => {
    // Student with a non-numeric phone that normalizePhone() rejects
    const stBadPhone = await insertStudent(simSchoolId, "INVALID", "nop@test.com");
    await insertFee(simSchoolId, stBadPhone, simSessionId, istDate(0));
    const result = await runDunningSimulation(simSchoolId);
    const smsEntries = result.entries.filter(e => e.channel === "sms" && e.issue !== null);
    expect(smsEntries.length).toBeGreaterThan(0);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// 11. Manual single-fee trigger
// ─────────────────────────────────────────────────────────────────────────────

describe("Integration — runDunningForSingleFee", () => {
  let manSchoolId = 0, manSessionId = 0, manStudentId = 0;

  beforeAll(async () => {
    manSchoolId  = await insertSchool();
    manSessionId = await insertSession(manSchoolId);
    manStudentId = await insertStudent(manSchoolId, BASE_PHONE, BASE_EMAIL);
  });
  afterEach(async () => {
    vi.restoreAllMocks();
    await db.delete(dunningLog).where(eq(dunningLog.schoolId, manSchoolId));
    await db.delete(notificationConfig).where(eq(notificationConfig.schoolId, manSchoolId));
    await db.delete(feeRecords).where(eq(feeRecords.schoolId, manSchoolId));
  });

  it("11a — manual trigger sends and logs correctly", async () => {
    vi.spyOn(global, "fetch").mockResolvedValue(new Response(JSON.stringify({ type: "success" }), { status: 200 }));
    const feeId = await insertFee(manSchoolId, manStudentId, manSessionId, istDate(0));
    await insertConfig(manSchoolId, { waEnabled: false, emailEnabled: false });
    const result = await runDunningForSingleFee(manSchoolId, feeId);
    expect(result.sent).toContain("sms");
    expect(await dunningLogCount(feeId, "sms", "D+0")).toBe(1);
  });

  it("11b — paid fee is skipped without sending", async () => {
    const feeId = await insertFee(manSchoolId, manStudentId, manSessionId, istDate(0));
    await markPaid(feeId);
    const result = await runDunningForSingleFee(manSchoolId, feeId);
    expect(result.skipped).toContain("Paid — no reminder needed");
    expect(result.sent.length).toBe(0);
  });

  it("11c — selected session rejects a fee from another session", async () => {
    const feeId = await insertFee(manSchoolId, manStudentId, manSessionId, istDate(0));
    const [otherSession] = await db.insert(academicSessions).values({
      schoolId: manSchoolId,
      sessionName: `Other-${Date.now()}`,
      startDate: "2027-04-01",
      endDate: "2028-03-31",
      isActive: false,
    }).returning({ id: academicSessions.id });

    await expect(
      runDunningForSingleFee(manSchoolId, feeId, otherSession.id),
    ).rejects.toThrow("does not belong to this school");

    await db.delete(academicSessions).where(eq(academicSessions.id, otherSession.id));
  });

  it("11d — cross-school access is rejected", async () => {
    const feeId = await insertFee(manSchoolId, manStudentId, manSessionId, istDate(0));
    const otherSchool = await insertSchool();
    await expect(runDunningForSingleFee(otherSchool, feeId)).rejects.toThrow("does not belong to this school");
    await db.delete(schools).where(eq(schools.id, otherSchool));
  });

  it("11e — manual trigger uses total amount (base + late fee)", async () => {
    const captured: string[] = [];
    vi.spyOn(global, "fetch").mockImplementation(async (url, init) => {
      if (String(url).includes("msg91.com/api/v2")) captured.push(JSON.parse((init as any).body).sms[0].message);
      return new Response(JSON.stringify({ type: "success" }), { status: 200 });
    });
    const feeId = await insertFee(manSchoolId, manStudentId, manSessionId, istDate(0), 3000, 200);
    await insertConfig(manSchoolId, { waEnabled: false, emailEnabled: false });
    await runDunningForSingleFee(manSchoolId, feeId);
    expect(captured[0]).toContain("3,200");
    expect(captured[0]).not.toContain("3,000");
  });
});
